USE ROLE ENT_PEOPLE_OWNER_{{ENVR}}_ROLE;
USE DATABASE ENT_STG_PEOPLE_{{DB_SUFFIX}};
USE SCHEMA LOAD_STG;

 CREATE OR REPLACE EXTERNAL TABLE LOAD_STG.TRM_PRACTICE_PERSON_TOPIC_FULL_EXT
(
	ID NUMBER AS ($1:id::NUMBER),
	PRACTICE_PERSON_ID NUMBER AS ($1:practice_person_id::NUMBER),
	TOPIC_ID NUMBER AS ($1:topic_id::NUMBER),
    PRACTICE_RECOMMENDED VARCHAR AS (NULLIF(($1:practice_recommended::VARCHAR),'')),
	FIRST_ALERT VARCHAR AS (NULLIF(($1:first_alert::VARCHAR),'')),
	CREATED_AT TIMESTAMP AS ($1:created_at::TIMESTAMP),
	UPDATED_AT TIMESTAMP AS ($1:updated_at::TIMESTAMP),
	CREATED_BY VARCHAR AS (NULLIF(($1:created_by::VARCHAR),'')),
	UPDATED_BY VARCHAR AS (NULLIF(($1:updated_by::VARCHAR),'')),
	RANK NUMBER AS ($1:rank::NUMBER)
)
location=@STG_PEOPLE/ksr/full/trm/practice_person_topic/
file_format=FF.PARQUET_FORMAT
;