USE ROLE ENT_PEOPLE_OWNER_{{ENVR}}_ROLE;
USE DATABASE ENT_PEOPLE_{{DB_SUFFIX}};

CREATE TABLE STG.PERSON_EXPERTISE_TOPIC_STG
(
	FMNO VARCHAR,
	TOPIC_ID NUMBER,
	TOPIC_NAME VARCHAR,
	TOPIC_DESCRIPTION VARCHAR,
	TOPIC_TAXONOMY_URL_ID VARCHAR,
	TAXONOMY_TAG_VALUE VARCHAR,
	TOPIC_TAXNOMY_TYPE VARCHAR, 
	TOPIC_PRACTICE_URL_ID VARCHAR, 
	START_DATE TIMESTAMP(0),
	END_DATE TIMESTAMP(0),
	CREATION_DATE TIMESTAMP(0) NOT NULL,
	UPDATE_DATE	TIMESTAMP(0) NOT NULL,
	CHANGE_HASH VARCHAR  NOT NULL
);