USE ROLE ENT_PEOPLE_OWNER_PROD_ROLE;
USE DATABASE ENT_PEOPLE_PROD_DB

CREATE OR REPLACE VIEW DATA.VW_PERSON_EXPERTISE_TOPIC(
	PERSON_EXPERTISE_TOPIC_ID,
	FMNO,
	TOPIC_ID,
	TOPIC_NAME,
	TOPIC_DESCRIPTION,
	TOPIC_TAXONOMY_URL_ID,
	TAXONOMY_TAG_VALUE,
	TOPIC_TAXNOMY_TYPE, 
	TOPIC_PRACTICE_URL_ID,
	PRACTICE_RECOMMENDED,
    FIRST_ALERT,
	START_DATE,
	END_DATE,
	CURRENT_RECORD_INDICATOR,
	CREATE_DATE ,
	UPDATE_DATE 
) COPY GRANTS as
SELECT 	PERSON_EXPERTISE_TOPIC_ID,
		FMNO,
		TOPIC_ID,
		TOPIC_NAME,
		TOPIC_DESCRIPTION,
		TOPIC_TAXONOMY_URL_ID,
		TAXONOMY_TAG_VALUE,
		TOPIC_TAXNOMY_TYPE, 
		TOPIC_PRACTICE_URL_ID,
		PRACTICE_RECOMMENDED,
		FIRST_ALERT,
		START_DATE,
		END_DATE,
		CURRENT_RECORD_INDICATOR,
		CREATION_DATE as CREATE_DATE,
		UPDATE_DATE 
FROM DATA.ED_PERSON_EXPERTISE_TOPIC_D WHERE END_DATE is null ;

GRANT SELECT ON DATA.VW_PERSON_EXPERTISE_TOPIC TO ROLE ENT_PEOPLE_USER_{{ENVR}}_ROLE;