USE ROLE ENT_PEOPLE_OWNER_{{ENVR}}_ROLE;
USE DATABASE ENT_PEOPLE_{{DB_SUFFIX}};

CREATE OR REPLACE VIEW LOAD.TRM_PRACTICE_PERSON_TOPIC_FULL_EXT_V
AS
SELECT 	ID,
		PRACTICE_PERSON_ID,
		TOPIC_ID,
		PRACTICE_RECOMMENDED,
		FIRST_ALERT,
        CREATED_BY,
        UPDATED_BY,
        CREATED_AT,
        UPDATED_AT,
		RANK
    FROM ENT_STG_PEOPLE_{{DB_SUFFIX}}.LOAD_STG.TRM_PRACTICE_PERSON_TOPIC_FULL_EXT;