GLOBAL="global"
ENVIRONMENT="environment"
JOB="job"
STAGES="stages"
CONTROL="control"
S3="s3"
DECODE_FMT="utf-8"
S3PREFIX="s3://"
DATEPARTPREFIX="date="
HOURPARTPREFIX="hour="
S3PATHDELIM="/"
HYPHEN="-"
BLANK=""
FULL="full"
INCR="incr"
SRC2TGT="Source2Target"
DYNAMODB="dynamodb"

